# Generated by Django 3.2.4 on 2021-06-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cs',
        ),
        migrations.DeleteModel(
            name='Cs_comment',
        ),
    ]
