# Generated by Django 3.2.4 on 2021-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210626_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
