# Generated by Django 3.2.4 on 2021-06-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cs_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='cs_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
