# Generated by Django 3.2.4 on 2021-06-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pet',
            field=models.CharField(blank=True, choices=[('Y', '있음'), ('N', '없음')], max_length=2),
        ),
    ]
