# Generated by Django 3.2.4 on 2021-06-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('emoticon_01', models.IntegerField()),
                ('emoticon_02', models.IntegerField()),
                ('emoticon_03', models.IntegerField()),
                ('emoticon_04', models.IntegerField()),
                ('emoticon_05', models.IntegerField()),
                ('pet_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet_page')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pet_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('voice', models.FileField(upload_to='')),
                ('deathday', models.DateField()),
                ('satatus', models.CharField(max_length=20)),
                ('pet_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pet.pet_page')),
            ],
        ),
    ]
