# Generated by Django 3.2.4 on 2021-06-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='satatus',
            new_name='status',
        ),
    ]
