# Generated by Django 3.2.4 on 2021-07-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoticon_01', models.PositiveIntegerField(default=0)),
                ('emoticon_02', models.PositiveIntegerField(default=0)),
                ('emoticon_03', models.PositiveIntegerField(default=0)),
                ('emoticon_04', models.PositiveIntegerField(default=0)),
                ('emoticon_05', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
